theme: jekyll-theme-architect
title: Adventures in Data Science
description: Hello! My name is Sarah, and I am a data science professional with 14+ years of experience in delivering actionable insights across healthcare, public sector, and research environments. In this blog, I plan to document my journey in data science, machine learning, and AI.
author: sxp189
